#!/bin/bash
# ===================================================================
#  Build MMForge.app for macOS
#
#  Called by tools/setup_env.py at the end of the installation. It can
#  also be run on its own:
#
#      bash tools/create_macos_app.sh
#
#  What it produces is a small wrapper, not a copy of MMForge: the app
#  simply opens MMForge.command from the project folder in Terminal.
#  That keeps a visible window for progress messages and gives the user
#  an obvious way to stop the server, while still providing a proper
#  icon in Launchpad, Spotlight and the Dock.
#
#  The app is BUILT here rather than shipped in the repository on
#  purpose. An .app that arrives inside a downloaded ZIP is flagged by
#  Gatekeeper and refused as "damaged or from an unidentified
#  developer". One that is created locally carries no such flag.
#
#  If the MMForge folder is moved or renamed later, run the installer
#  again to rebuild the app with the new path.
# ===================================================================

set -u

# tools/create_macos_app.sh -> tools/ -> project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="${1:-$(dirname "$SCRIPT_DIR")}"

LAUNCHER="$ROOT/MMForge.command"
SOURCE_PNG="$ROOT/tools/mmforge.png"

APPS_DIR="$HOME/Applications"
APP="$APPS_DIR/MMForge.app"

if [ ! -f "$LAUNCHER" ]; then
    echo "  Could not find $LAUNCHER - the app was not created."
    exit 1
fi

# --- 1) Rebuild the bundle from scratch -----------------------------
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS"
mkdir -p "$APP/Contents/Resources"

# --- 2) Info.plist ---------------------------------------------------
cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>MMForge</string>
    <key>CFBundleDisplayName</key>
    <string>MMForge</string>
    <key>CFBundleIdentifier</key>
    <string>cz.upol.optics.mmforge</string>
    <key>CFBundleVersion</key>
    <string>2.1.0</string>
    <key>CFBundleShortVersionString</key>
    <string>2.1.0</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleExecutable</key>
    <string>MMForge</string>
    <key>CFBundleIconFile</key>
    <string>mmforge</string>
    <key>LSMinimumSystemVersion</key>
    <string>11.0</string>
    <key>NSHighResolutionCapable</key>
    <true/>
</dict>
</plist>
PLIST

# --- 3) The executable inside the bundle -----------------------------
cat > "$APP/Contents/MacOS/MMForge" <<LAUNCH
#!/bin/bash
# Generated by tools/create_macos_app.sh - do not edit.
# Opens the real launcher in Terminal so the user can see progress
# messages and can stop MMForge by closing the window.
exec open -a Terminal "$LAUNCHER"
LAUNCH
chmod +x "$APP/Contents/MacOS/MMForge"

# --- 4) Icon ---------------------------------------------------------
# sips and iconutil are part of macOS, so no extra tools are needed.
# If anything here fails the app still works, it just uses the default
# icon - never let a cosmetic step break the installation.
if [ -f "$SOURCE_PNG" ]; then
    ICONSET="$(mktemp -d)/mmforge.iconset"
    mkdir -p "$ICONSET"

    icon_ok=1
    for size in 16 32 128 256 512; do
        double=$((size * 2))
        sips -z "$size" "$size" "$SOURCE_PNG" \
            --out "$ICONSET/icon_${size}x${size}.png" >/dev/null 2>&1 || icon_ok=0
        sips -z "$double" "$double" "$SOURCE_PNG" \
            --out "$ICONSET/icon_${size}x${size}@2x.png" >/dev/null 2>&1 || icon_ok=0
    done

    if [ "$icon_ok" -eq 1 ]; then
        iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/mmforge.icns" >/dev/null 2>&1 \
            || echo "  Note: could not build the icon; using the default one."
    else
        echo "  Note: could not resize the icon; using the default one."
    fi

    rm -rf "$(dirname "$ICONSET")"
fi

# Nudge Finder into noticing the new bundle and its icon.
touch "$APP"

echo "  MMForge app created:"
echo "      $APP"
echo ""
echo "  Open Finder > Go > Applications to find it."
echo "  Drag it onto your Dock to keep it one click away."
